In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\Users\Roli\Desktop\ML learning\medicare\dataset\Training.csv\Training.csv')

In [3]:
df.shape

(4920, 133)

In [4]:
df.head(3)

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0             0                    0   
1           0         0             0                    0   
2           0         0             0                    0   

   small_dents_in_nails  inflammatory_nails  blister  red_sore_around_nose  \
0                     0                   0        0                     0   
1                     0                   0        0                     0   
2                     0                   0        0                     0   

   yellow_crust_ooze         prognosis  
0                  0  Fungal infection  
1                  0  Fungal infection  
2                  0  Fungal infection  

[3 rows x 133 columns]

In [5]:
df.isnull().sum()

itching                 0
skin_rash               0
nodal_skin_eruptions    0
continuous_sneezing     0
shivering               0
                       ..
inflammatory_nails      0
blister                 0
red_sore_around_nose    0
yellow_crust_ooze       0
prognosis               0
Length: 133, dtype: int64

In [6]:
df['prognosis'].unique()

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes ',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension ', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [7]:
# total 41 unique type of deseises
df['prognosis'].unique().shape

(41,)

### Train-test-split

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [10]:
X = df.iloc[:, :132]
y = df.iloc[:, -1:]

In [11]:
X.head()

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   pus_filled_pimples  blackheads  scurring  skin_peeling  \
0                   0           0         0             0   
1                   0           0         0             0   
2                   0           0         0             0   
3                   0           0         0             0   
4                   0           0         0             0   

   silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
0                    0                     0                   0        0   
1                    0                     0                   0        0   
2                    0                     0                   0        0   
3                    0                     0                   0        0   
4                    0                     0                   0        0   

   red_sore_around_nose  yellow_crust_ooze  
0                     0                  0  
1                     0                  0  
2                     0                  0  
3                     0                  0  
4                     0                  0  

[5 rows x 132 columns]

In [12]:
y.head()

prognosis
0  Fungal infection
1  Fungal infection
2  Fungal infection
3  Fungal infection
4  Fungal infection

In [13]:
y.shape

(4920, 1)

In [14]:
X.shape

(4920, 132)

### Encoding Label

In [16]:
le = LabelEncoder()
Y = le.fit_transform(y.values.ravel())

In [17]:
Y

array([15, 15, 15, ..., 38, 35, 27])

In [18]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 20)

In [19]:
X_train.shape, X_test.shape, Y_train.shape, Y_test.shape

((3936, 132), (984, 132), (3936,), (984,))

### Train model on diffirent algorithms

In [21]:
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.metrics import confusion_matrix
from sklearn.utils import shuffle
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier

In [22]:
# Create and train the SVC model
model_svc = SVC(kernel='linear', C=1.0, random_state=42)
model_svc.fit(X_train, Y_train)

# Make predictions
y_pred = model_svc.predict(X_test)

# Evaluate the model
print("Accuracy:", accuracy_score(Y_test, y_pred))

# Calculate confusion matrix
cm = confusion_matrix(Y_test, y_pred)
print(f"{model_svc} Confusion Matrix:")

Accuracy: 1.0
SVC(kernel='linear', random_state=42) Confusion Matrix:


In [23]:
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(X_train, Y_train)
y_predict_val = knn_model.predict(X_test)

print("Accuracy score is : ", accuracy_score(Y_test, y_predict_val))

print("\nClassification Report:\n")
print(metrics.classification_report(Y_test, y_predict_val))

print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_predict_val))

Accuracy score is :  1.0

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        24
           1       1.00      1.00      1.00        27
           2       1.00      1.00      1.00        18
           3       1.00      1.00      1.00        29
           4       1.00      1.00      1.00        28
           5       1.00      1.00      1.00        26
           6       1.00      1.00      1.00        25
           7       1.00      1.00      1.00        25
           8       1.00      1.00      1.00        21
           9       1.00      1.00      1.00        35
          10       1.00      1.00      1.00        24
          11       1.00      1.00      1.00        30
          12       1.00      1.00      1.00        23
          13       1.00      1.00      1.00        18
          14       1.00      1.00      1.00        19
          15       1.00      1.00      1.00        24
          16       1.00      1.

In [24]:
svc_model = SVC()
svc_model.fit(X_train, Y_train)
y_predict_val = svc_model.predict(X_test)

print("Accuracy score is : ", accuracy_score(Y_test, y_predict_val))

# print("\nClassification Report:\n")
# print(metrics.classification_report(Y_test, y_predict_val))

print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_predict_val))


Accuracy score is :  1.0

Confusion Matrix:
[[24  0  0 ...  0  0  0]
 [ 0 27  0 ...  0  0  0]
 [ 0  0 18 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0 33  0]
 [ 0  0  0 ...  0  0 22]]


In [25]:
rf = RandomForestClassifier(n_estimators=100,max_depth=7,min_samples_split=5, random_state=42)
rf.fit(X_train, Y_train)
y_predict_val = rf.predict(X_test)

print("Accuracy score is : ", accuracy_score(Y_test, y_predict_val))

print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_predict_val))


Accuracy score is :  0.9939024390243902

Confusion Matrix:
[[24  0  0 ...  0  0  0]
 [ 0 27  0 ...  0  0  0]
 [ 0  0 18 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0 33  0]
 [ 0  0  0 ...  0  0 22]]


In [26]:
LR = LogisticRegression(C=100, random_state=14)
LR.fit(X_train, Y_train)
y_predict_val = LR.predict(X_test)

print("Accuracy score is : ", accuracy_score(Y_test, y_predict_val))

print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_predict_val))


Accuracy score is :  1.0

Confusion Matrix:
[[24  0  0 ...  0  0  0]
 [ 0 27  0 ...  0  0  0]
 [ 0  0 18 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0 33  0]
 [ 0  0  0 ...  0  0 22]]


In [27]:
naive = GaussianNB()
naive.fit(X_train, Y_train)
y_predict_val = naive.predict(X_test)

print("Accuracy score is : ", accuracy_score(Y_test, y_predict_val))

print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_predict_val))

Accuracy score is :  1.0

Confusion Matrix:
[[24  0  0 ...  0  0  0]
 [ 0 27  0 ...  0  0  0]
 [ 0  0 18 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0 33  0]
 [ 0  0  0 ...  0  0 22]]


In [28]:
gradient = GradientBoostingClassifier(n_estimators=100,max_depth=None,min_samples_split=2, random_state=0)
gradient.fit(X_train, Y_train)
y_predict_val = gradient.predict(X_test)

print("Accuracy score is : ", accuracy_score(Y_test, y_predict_val))

print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_predict_val))

Accuracy score is :  1.0

Confusion Matrix:
[[24  0  0 ...  0  0  0]
 [ 0 27  0 ...  0  0  0]
 [ 0  0 18 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0 33  0]
 [ 0  0  0 ...  0  0 22]]


In [29]:
decision = DecisionTreeClassifier()
decision.fit(X_train, Y_train)
y_predict_val = decision.predict(X_test)

print("Accuracy score is : ", accuracy_score(Y_test, y_predict_val))

print("\nConfusion Matrix:")
print(confusion_matrix(Y_test, y_predict_val))

Accuracy score is :  1.0

Confusion Matrix:
[[24  0  0 ...  0  0  0]
 [ 0 27  0 ...  0  0  0]
 [ 0  0 18 ...  0  0  0]
 ...
 [ 0  0  0 ... 24  0  0]
 [ 0  0  0 ...  0 33  0]
 [ 0  0  0 ...  0  0 22]]


### save the model(any) with highest accuracy

In [62]:
import pickle
pickle.dump(svc_model, open('models\svc_model.pickle', 'wb'))

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Roli\AppData\Local\Temp\ipykernel_10492\1514302944.py:2: SyntaxWarning: invalid escape sequence '\s'
  pickle.dump(svc_model, open('models\svc_model.pickle', 'wb'))


### Load the model to test

In [65]:
svc_model = pickle.load(open('models\svc_model.pickle','rb'))

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
C:\Users\Roli\AppData\Local\Temp\ipykernel_10492\860270052.py:1: SyntaxWarning: invalid escape sequence '\s'
  svc_model = pickle.load(open('models\svc_model.pickle','rb'))


In [67]:
X_test

itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  \
4037        0          0                     0                    0   
4191        0          0                     0                    0   
432         0          0                     0                    0   
1266        1          0                     0                    0   
3765        0          0                     0                    0   
...       ...        ...                   ...                  ...   
2111        0          0                     0                    0   
2923        0          0                     0                    0   
1054        0          0                     0                    0   
1340        0          0                     0                    0   
3418        0          0                     0                    0   

      shivering  chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  \
4037          0       0           1             0        0                 0   
4191          0       0           0             0        0                 0   
432           0       0           0             1        1                 0   
1266          0       0           0             0        0                 0   
3765          0       0           1             0        0                 0   
...         ...     ...         ...           ...      ...               ...   
2111          0       0           0             0        0                 0   
2923          0       0           0             0        0                 0   
1054          0       0           1             0        0                 0   
1340          0       0           0             0        1                 0   
3418          0       1           0             0        0                 0   

      ...  pus_filled_pimples  blackheads  scurring  skin_peeling  \
4037  ...                   0           0         0             0   
4191  ...                   0           0         0             0   
432   ...                   0           0         0             0   
1266  ...                   0           0         0             0   
3765  ...                   0           0         0             0   
...   ...                 ...         ...       ...           ...   
2111  ...                   0           0         0             0   
2923  ...                   0           0         0             0   
1054  ...                   0           0         0             0   
1340  ...                   0           0         0             0   
3418  ...                   0           0         0             0   

      silver_like_dusting  small_dents_in_nails  inflammatory_nails  blister  \
4037                    0                     0                   0        0   
4191                    0                     0                   0        0   
432                     0                     0                   0        0   
1266                    0                     0                   0        0   
3765                    0                     0                   0        0   
...                   ...                   ...                 ...      ...   
2111                    0                     0                   0        0   
2923                    0                     0                   0        0   
1054                    0                     0                   0        0   
1340                    0                     0                   0        0   
3418                    0                     0                   0        0   

      red_sore_around_nose  yellow_crust_ooze  
4037                     0                  0  
4191                     0                  0  
432                      0                  0  
1266                     0                  0  
3765                     0                  0  
...                    ...                ...  
2111                     0                  0  
2923              

### test our model

In [75]:
inputTestSVC = X_test.iloc[0].values.reshape(1, -1)
print(inputTestSVC)

[[0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1
  0 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [77]:
svc_model.predict(inputTestSVC)

C:\Users\Roli\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([40])

In [81]:
print("Predicted Label : ", svc_model.predict(inputTestSVC))
print("Actual Label : ",  Y_test[0])

# both are same , means model predicting correct desease

Predicted Label :  [40]
Actual Label :  40


C:\Users\Roli\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


### load other datasets needed 


In [120]:
sym_des = pd.read_csv(r"dataset\symtoms_df.csv")
sym_des.head(5)

Unnamed: 0           Disease   Symptom_1              Symptom_2  \
0           0  Fungal infection     itching              skin_rash   
1           1  Fungal infection   skin_rash   nodal_skin_eruptions   
2           2  Fungal infection     itching   nodal_skin_eruptions   
3           3  Fungal infection     itching              skin_rash   
4           4  Fungal infection     itching              skin_rash   

               Symptom_3             Symptom_4  
0   nodal_skin_eruptions   dischromic _patches  
1    dischromic _patches                   NaN  
2    dischromic _patches                   NaN  
3    dischromic _patches                   NaN  
4   nodal_skin_eruptions                   NaN

In [106]:
precautions = pd.read_csv(r"dataset\precautions_df.csv")
precautions.head(5)

Unnamed: 0         Disease                      Precaution_1  \
0           0   Drug Reaction                   stop irritation   
1           1         Malaria          Consult nearest hospital   
2           2         Allergy                    apply calamine   
3           3  Hypothyroidism                     reduce stress   
4           4       Psoriasis  wash hands with warm soapy water   

                   Precaution_2        Precaution_3  \
0      consult nearest hospital    stop taking drug   
1               avoid oily food  avoid non veg food   
2       cover area with bandage                 NaN   
3                      exercise         eat healthy   
4  stop bleeding using pressure      consult doctor   

                  Precaution_4  
0                    follow up  
1           keep mosquitos out  
2  use ice to compress itching  
3             get proper sleep  
4                   salt baths

In [122]:
workout = pd.read_csv(r"dataset\workout_df.csv")
workout.head(5)

Unnamed: 0.1  Unnamed: 0           disease                    workout
0             0           0  Fungal infection         Avoid sugary foods
1             1           1  Fungal infection         Consume probiotics
2             2           2  Fungal infection  Increase intake of garlic
3             3           3  Fungal infection     Include yogurt in diet
4             4           4  Fungal infection      Limit processed foods

In [104]:
description = pd.read_csv(r"dataset\description.csv")
description.head(5)

Disease                                        Description
0     Fungal infection  Fungal infection is a common skin condition ca...
1              Allergy  Allergy is an immune system reaction to a subs...
2                 GERD  GERD (Gastroesophageal Reflux Disease) is a di...
3  Chronic cholestasis  Chronic cholestasis is a condition where bile ...
4        Drug Reaction  Drug Reaction occurs when the body reacts adve...

In [116]:
medications = pd.read_csv(r"dataset/medications.csv")
medications.head(5)

Disease                                         Medication
0     Fungal infection  ['Antifungal Cream', 'Fluconazole', 'Terbinafi...
1              Allergy  ['Antihistamines', 'Decongestants', 'Epinephri...
2                 GERD  ['Proton Pump Inhibitors (PPIs)', 'H2 Blockers...
3  Chronic cholestasis  ['Ursodeoxycholic acid', 'Cholestyramine', 'Me...
4        Drug Reaction  ['Antihistamines', 'Epinephrine', 'Corticoster...

In [118]:
diets = pd.read_csv(r"dataset/diets.csv")
diets.head(5)

Disease                                               Diet
0     Fungal infection  ['Antifungal Diet', 'Probiotics', 'Garlic', 'C...
1              Allergy  ['Elimination Diet', 'Omega-3-rich foods', 'Vi...
2                 GERD  ['Low-Acid Diet', 'Fiber-rich foods', 'Ginger'...
3  Chronic cholestasis  ['Low-Fat Diet', 'High-Fiber Diet', 'Lean prot...
4        Drug Reaction  ['Antihistamine Diet', 'Omega-3-rich foods', '...

### Main function to show Disease

In [132]:
symptoms_dict = {'itching': 0, 'skin_rash': 1, 'nodal_skin_eruptions': 2, 'continuous_sneezing': 3, 'shivering': 4, 'chills': 5, 'joint_pain': 6, 'stomach_pain': 7, 'acidity': 8, 'ulcers_on_tongue': 9, 'muscle_wasting': 10, 'vomiting': 11, 'burning_micturition': 12, 'spotting_ urination': 13, 'fatigue': 14, 'weight_gain': 15, 'anxiety': 16, 'cold_hands_and_feets': 17, 'mood_swings': 18, 'weight_loss': 19, 'restlessness': 20, 'lethargy': 21, 'patches_in_throat': 22, 'irregular_sugar_level': 23, 'cough': 24, 'high_fever': 25, 'sunken_eyes': 26, 'breathlessness': 27, 'sweating': 28, 'dehydration': 29, 'indigestion': 30, 'headache': 31, 'yellowish_skin': 32, 'dark_urine': 33, 'nausea': 34, 'loss_of_appetite': 35, 'pain_behind_the_eyes': 36, 'back_pain': 37, 'constipation': 38, 'abdominal_pain': 39, 'diarrhoea': 40, 'mild_fever': 41, 'yellow_urine': 42, 'yellowing_of_eyes': 43, 'acute_liver_failure': 44, 'fluid_overload': 45, 'swelling_of_stomach': 46, 'swelled_lymph_nodes': 47, 'malaise': 48, 'blurred_and_distorted_vision': 49, 'phlegm': 50, 'throat_irritation': 51, 'redness_of_eyes': 52, 'sinus_pressure': 53, 'runny_nose': 54, 'congestion': 55, 'chest_pain': 56, 'weakness_in_limbs': 57, 'fast_heart_rate': 58, 'pain_during_bowel_movements': 59, 'pain_in_anal_region': 60, 'bloody_stool': 61, 'irritation_in_anus': 62, 'neck_pain': 63, 'dizziness': 64, 'cramps': 65, 'bruising': 66, 'obesity': 67, 'swollen_legs': 68, 'swollen_blood_vessels': 69, 'puffy_face_and_eyes': 70, 'enlarged_thyroid': 71, 'brittle_nails': 72, 'swollen_extremeties': 73, 'excessive_hunger': 74, 'extra_marital_contacts': 75, 'drying_and_tingling_lips': 76, 'slurred_speech': 77, 'knee_pain': 78, 'hip_joint_pain': 79, 'muscle_weakness': 80, 'stiff_neck': 81, 'swelling_joints': 82, 'movement_stiffness': 83, 'spinning_movements': 84, 'loss_of_balance': 85, 'unsteadiness': 86, 'weakness_of_one_body_side': 87, 'loss_of_smell': 88, 'bladder_discomfort': 89, 'foul_smell_of urine': 90, 'continuous_feel_of_urine': 91, 'passage_of_gases': 92, 'internal_itching': 93, 'toxic_look_(typhos)': 94, 'depression': 95, 'irritability': 96, 'muscle_pain': 97, 'altered_sensorium': 98, 'red_spots_over_body': 99, 'belly_pain': 100, 'abnormal_menstruation': 101, 'dischromic _patches': 102, 'watering_from_eyes': 103, 'increased_appetite': 104, 'polyuria': 105, 'family_history': 106, 'mucoid_sputum': 107, 'rusty_sputum': 108, 'lack_of_concentration': 109, 'visual_disturbances': 110, 'receiving_blood_transfusion': 111, 'receiving_unsterile_injections': 112, 'coma': 113, 'stomach_bleeding': 114, 'distention_of_abdomen': 115, 'history_of_alcohol_consumption': 116, 'fluid_overload.1': 117, 'blood_in_sputum': 118, 'prominent_veins_on_calf': 119, 'palpitations': 120, 'painful_walking': 121, 'pus_filled_pimples': 122, 'blackheads': 123, 'scurring': 124, 'skin_peeling': 125, 'silver_like_dusting': 126, 'small_dents_in_nails': 127, 'inflammatory_nails': 128, 'blister': 129, 'red_sore_around_nose': 130, 'yellow_crust_ooze': 131}
diseases_list = {15: 'Fungal infection', 4: 'Allergy', 16: 'GERD', 9: 'Chronic cholestasis', 14: 'Drug Reaction', 33: 'Peptic ulcer diseae', 1: 'AIDS', 12: 'Diabetes ', 17: 'Gastroenteritis', 6: 'Bronchial Asthma', 23: 'Hypertension ', 30: 'Migraine', 7: 'Cervical spondylosis', 32: 'Paralysis (brain hemorrhage)', 28: 'Jaundice', 29: 'Malaria', 8: 'Chicken pox', 11: 'Dengue', 37: 'Typhoid', 40: 'hepatitis A', 19: 'Hepatitis B', 20: 'Hepatitis C', 21: 'Hepatitis D', 22: 'Hepatitis E', 3: 'Alcoholic hepatitis', 36: 'Tuberculosis', 10: 'Common Cold', 34: 'Pneumonia', 13: 'Dimorphic hemmorhoids(piles)', 18: 'Heart attack', 39: 'Varicose veins', 26: 'Hypothyroidism', 24: 'Hyperthyroidism', 25: 'Hypoglycemia', 31: 'Osteoarthristis', 5: 'Arthritis', 0: '(vertigo) Paroymsal  Positional Vertigo', 2: 'Acne', 38: 'Urinary tract infection', 35: 'Psoriasis', 27: 'Impetigo'}


# helper funtions to find precaution, description, medicine, diet and workout for a particular disease
def helper(dis):
    desc = description[description['Disease'] == predicted_disease]['Description']
    desc = " ".join([w for w in desc])

    pre = precautions[precautions['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
    pre = [col for col in pre.values]

    med = medications[medications['Disease'] == dis]['Medication']
    med = [med for med in med.values]

    die = diets[diets['Disease'] == dis]['Diet']
    die = [die for die in die.values]

    wrkout = workout[workout['disease'] == dis] ['workout']

    return desc,pre,med,die,wrkout


# Model Prediction function(Main function)....
def get_predicted_value(patient_symptoms):
    input_vector = np.zeros(len(symptoms_dict))
    for item in patient_symptoms:
        input_vector[symptoms_dict[item]] = 1
    return diseases_list[svc_model.predict([input_vector])[0]]

### Predict the disease of patient on the basis of symptoms

In [1]:
# Test input:
symptoms = input("Enter the symptoms of patient : ")
user_symptoms = [s.strip() for s in symptoms.split(',')]
user_symptoms = [symptom.strip("[]' ") for symptom in user_symptoms]
predicted_disease = get_predicted_value(user_symptoms)

Enter the symptoms of patient :  joint_pain


NameError: name 'get_predicted_value' is not defined

In [138]:
print("Patient is suffering from", predicted_disease)

Patient is suffering from Allergy


### Now give all the advise, like desciption, precautions, diets, workout and medicine for the predicted disease of patient

In [141]:
medicalAdvise = helper(predicted_disease)
print(medicalAdvise)

('Allergy is an immune system reaction to a substance in the environment.', [array(['apply calamine', 'cover area with bandage', nan,
       'use ice to compress itching'], dtype=object)], ["['Antihistamines', 'Decongestants', 'Epinephrine', 'Corticosteroids', 'Immunotherapy']"], ["['Elimination Diet', 'Omega-3-rich foods', 'Vitamin C-rich foods', 'Quercetin-rich foods', 'Probiotics']"], 10             Avoid allergenic foods
11    Consume anti-inflammatory foods
12        Include omega-3 fatty acids
13                      Stay hydrated
14        Eat foods rich in vitamin C
15       Include quercetin-rich foods
16                Consume local honey
17              Limit processed foods
18             Include ginger in diet
19         Avoid artificial additives
Name: workout, dtype: object)


### Beutify the visual representation

In [193]:
desc,pre,med,die,wrkout = helper(predicted_disease)

print("....................................Description of Disease.................................................")
print(desc)

print("\n..................................Precaution for the Patient.............................................")
count = 1
for p in pre[0]:
    print(count, " : ", p)
    count+=1

print("\n..................................Medicines for the Disease..............................................")
for m_i in med:
    print(count, ": ", m_i)
    count += 1

print("\n..................................Diet for the Patient...................................................")
for d_i in die:
    print(count, ": ", d_i)
    count += 1

print("\n..................................Needed Workout Suggetions.............................................")
for w_i in wrkout:
    print(count, ": ", w_i)
    count += 1

....................................Description of Disease.................................................
Allergy is an immune system reaction to a substance in the environment.

..................................Precaution for the Patient.............................................
1  :  apply calamine
2  :  cover area with bandage
3  :  nan
4  :  use ice to compress itching

..................................Medicines for the Disease..............................................
5 :  ['Antihistamines', 'Decongestants', 'Epinephrine', 'Corticosteroids', 'Immunotherapy']

..................................Diet for the Patient...................................................
6 :  ['Elimination Diet', 'Omega-3-rich foods', 'Vitamin C-rich foods', 'Quercetin-rich foods', 'Probiotics']

..................................Needed Workout Suggetions.............................................
7 :  Avoid allergenic foods
8 :  Consume anti-inflammatory foods
9 :  Include omega-3 fatty acid

In [195]:
import sklearn
print(sklearn.__version__)

1.5.2
